language: julia
os:
  - linux
julia:
  - 1
jobs:
  include:
    - stage "Tests"
      script:
        - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
        - julia --project -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true)';
    - stage: "Documentation"
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
